apiVersion: apps/v1
kind: Deployment
metadata:
  name: zork-deployment
  labels:
    app: zork
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zork
  template:
    metadata:
      labels:
        app: zork
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
